# Generated by Django 5.0 on 2023-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('follow-up', 'Follow-UP')], default='New', max_length=30),
        ),
    ]
