# Generated by Django 5.0 on 2023-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_address_user_city_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=30),
        ),
    ]
